//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallOut
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Numbers
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PolNum { get; set; }
        public string FireNum { get; set; }
        public string HealthNum { get; set; }
    }
}
